# Generated by Django 4.1.1 on 2023-04-29 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hstariff',
            name='tariff_rate',
            field=models.DecimalField(decimal_places=2, help_text='Tariff rate of HS code and origin', max_digits=5),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1000)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('distributor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
                'permissions': [('can_edit_items', 'Can edit owned items')],
            },
        ),
    ]
