# Generated by Django 4.1.1 on 2023-05-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforma', '0003_alter_distributor_distributor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='registration_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Forwarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('registration_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
                'permissions': [('can_edit_packages', 'Can edit owned packages')],
            },
        ),
    ]
