# Generated by Django 4.1.1 on 2023-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0004_distributor_registration_code_forwarder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarder',
            name='registration_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
