# Generated by Django 4.1.1 on 2023-05-01 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platforma', '0005_alter_forwarder_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarder',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'forwarder'}, on_delete=django.db.models.deletion.CASCADE, related_name='forwarder', to=settings.AUTH_USER_MODEL),
        ),
    ]
