# Generated by Django 4.1.1 on 2023-05-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='avatar',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='forwarder',
            name='avatar',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
