# Generated by Django 4.1.1 on 2023-05-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0009_customer_avatar_distributor_avatar_forwarder_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, choices=[('Central Europe', 'Bulgaria, Czech Republic, Romania, Slovakia'), ('Northern Europe', 'Denmark, Finland, Ireland, Sweden'), ('Southern Europe', 'Croatia, Greece, Italy, Portugal, Spain'), ('Western Europe', 'Austria, Belgium, France, Germany, Netherlands, Switzerland'), ('Eastern Europe', 'Estonia, Latvia, Lithuania, Poland')], default='Northern Europe', help_text='Location of customer to determine delivery expences', max_length=20, verbose_name='Statusas'),
        ),
    ]
