# Generated by Django 4.1.1 on 2023-05-02 20:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0013_item_gross_weight_item_net_weight_item_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('ed', 'Economy express'), ('ed', 'Express delivery'), ('dp', 'Drop off/pick up points')], help_text='Freight service', max_length=2, verbose_name='Delivery')),
                ('region', models.CharField(choices=[('ce', 'Central Europe'), ('ne', 'Northern Europe'), ('se', 'Southern Europe'), ('we', 'Western Europe'), ('ee', 'Eastern Europe')], help_text='Delivery location', max_length=2, verbose_name='Region')),
                ('freight_cost_vkg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cheargable weight or volume, whatever is bigger', max_digits=4, verbose_name='Freight cost v/kg')),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforma.distributor')),
                ('forwarder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforma.forwarder')),
            ],
        ),
    ]
