# Generated by Django 4.1.1 on 2023-05-03 07:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0015_alter_contractdelivery_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, verbose_name='Gross Weight'),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, verbose_name='Net Weight'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforma.customer')),
                ('distributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforma.distributor')),
                ('items', models.ManyToManyField(to='platforma.item')),
            ],
        ),
    ]
