# Generated by Django 4.1.1 on 2023-05-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0016_alter_item_gross_weight_alter_item_net_weight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['distributor', 'name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='distributor_id',
        ),
        migrations.AddField(
            model_name='item',
            name='distributor',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='platforma.distributor'),
            preserve_default=False,
        ),
    ]
