# Generated by Django 4.1.1 on 2023-05-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0017_alter_item_options_remove_item_distributor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforma.distributor'),
        ),
    ]
