# Generated by Django 4.1.1 on 2023-05-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0018_alter_item_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforma.shoppingcart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforma.item')),
            ],
        ),
    ]
