# Generated by Django 4.1.1 on 2023-05-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0020_remove_shoppingcart_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='distributor_id',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='distributor',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.PROTECT, to='platforma.distributor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('distributor', 'cart', 'item')},
        ),
    ]
