# Generated by Django 4.1.1 on 2023-05-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0022_alter_shoppingcartitem_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='customer',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='platforma.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='distributor',
            field=models.OneToOneField(default=24, on_delete=django.db.models.deletion.PROTECT, to='platforma.distributor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('cart', 'item')},
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='distributor',
        ),
    ]
