# Generated by Django 4.1.1 on 2023-05-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0024_alter_shoppingcart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platforma.distributor'),
        ),
    ]
