# Generated by Django 4.1.1 on 2023-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0026_alter_contractdelivery_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='_cart_delivery_type',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
