# Generated by Django 4.1.1 on 2023-05-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0027_shoppingcart__cart_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='_cart_delivery_type',
            new_name='cart_delivery_type',
        ),
    ]
